name: Actualizar JSON desde Google Sheets

permissions:
  contents: write  # Necesario para poder hacer push
  actions: read
  checks: read

on:
  schedule:
    - cron: "0 10 * * *"   # 07:00 Buenos Aires
    - cron: "0 22 * * *"   # 19:00 Buenos Aires
  workflow_dispatch:     # Permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install gspread pandas oauth2client

      - name: Ejecutar script Portofino
        run: python script_portofino.py
        env:
          GOOGLE_CREDENTIALS_ACTUALIZADOR: ${{ secrets.GOOGLE_CREDENTIALS_ACTUALIZADOR }}

      - name: Ejecutar script Terranova
        run: python script_terranova.py
        env:
          GOOGLE_CREDENTIALS_ACTUALIZADOR: ${{ secrets.GOOGLE_CREDENTIALS_ACTUALIZADOR }}    

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit y Push cambios
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Actualización automática de precios" || echo "No hay cambios para commitear"
          git push https://x-access-token:${GH_PAT}@github.com/Sarif-arg/actualizador-de-precios.git HEAD:main
