name: Actualizar JSON desde Google Sheets

on:
  schedule:
    - cron: "0 12 * * *"  # Todos los días a las 12:00 UTC
  workflow_dispatch:     # Permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install gspread pandas oauth2client

      - name: Ejecutar script Python
        run: python script.py
        env:
          GOOGLE_CREDENTIALS_ACTUALIZADOR: ${{ secrets.GOOGLE_CREDENTIALS_ACTUALIZADOR }}

      - name: Commit & Push cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add datos.json
          git commit -m "Actualización automática de JSON"
          git push https://$GH_PAT@github.com/${{ github.repository }} HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        continue-on-error: true